# Generated by Django 5.1.4 on 2025-01-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('duration_field', models.DurationField()),
                ('big_auto_field', models.BigAutoField(primary_key=True, serialize=False)),
                ('many_to_many_field', models.ManyToManyField(to='modelapp.student')),
            ],
        ),
    ]
