# Generated by Django 5.1.4 on 2025-01-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='task.taskmodel'),
        ),
    ]
